---
title: "01_primer"
author: Jonas Ackermann
output: html_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r}
char <- "I am a person"
print(char)
```   

```{r}
log(1)
log(0)
log(exp(1))
log(-5)
-log(5)
log(1/5)
```
```{r}
?log
?log10
```

```{r}
a <- 5
b <- 13
c_sq <- (a*a) + (b*b)
c <- sqrt(c_sq)
print(c)

pyth <- function(a, b) {
  c_sq <- (a*a) + (b*b)
  sqrt(c_sq)
  # Do not need to return manually
  #c <- sqrt(c_sq)
 #return(c)
}
pyth(a = 5, b = 13)
```

## Sequences

```{r}
x1 = 1:10
```
```{r}
x2 = 1:12
x2[0]
x2[2]
```
```{r}
x3 = seq(from = 1, to = 10, by = 2)
x3
```
```{r}
x4 = seq(from = 1, by = 2, length.out = 19)
length(x4)
rep(1, 10)
```
```{r}
seq(from = -6, to = 6, by = 2)
x <- seq(from = -4.8, to = -3.43, length.out = 8)
length(x)
```
```{r}
x <- data.frame(hello = 1:10)
y <- cbind(x, world = 2:11)
print(y)
```
```{r}
pia <- c("Charlotte", "Mike", "Dad", "MV")
why <- c("da best", "good guy", "always tried", "hella smart")
data.frame(x = pia, y = why)
```

```{r}
getwd()
dat = read.table("../data/Lab1_frogs.txt",header=TRUE)
write.table(dat,"my_frogs.csv",row.names=FALSE,sep=",")     ## save as CSV
```
```{r}
?read.table
met <- read.table("../data/met_hourly.csv", row.names = NULL) # force not using row names
write.table(x,"exes.csv",row.names=FALSE,sep=",")
```
